name: Update IV Analysis

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual trigger
  push:
    paths:
      - 'data/vol_premium.csv'
      - 'data/hist_iv_analysis.csv'
      - 'utils/update_readme.py'

# Add permissions to push to the repository
permissions:
  contents: write

jobs:
  update-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        # Ensure we have full git history and can push back
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .  # Install the package in editable mode
        
    - name: Create data directory
      run: mkdir -p data
        
    - name: Run analysis scripts
      run: |
        python -m utils.get_vol_data
        python -m utils.get_hist_iv
        
    - name: Update README
      if: contains(github.event.push.changes, 'data/vol_premium.csv') || contains(github.event.push.changes, 'data/hist_iv_analysis.csv') || contains(github.event.push.changes, 'utils/update_readme.py')
      run: |
        python -m utils.update_readme
        
    - name: Commit and push changes
      env:
        # Use GitHub Actions token for authentication
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add -f README.md data/vol_premium.csv data/hist_iv_analysis.csv
        git commit -m "Update IV analysis" || exit 0
        git push
