name: Update IV Analysis

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual trigger
  push:
    paths:
      - 'data/**/*.csv'  # Any CSV file in data directory
      - 'utils/**/*.py'  # Any Python file in utils directory

# Add permissions to push to the repository
permissions:
  contents: write

jobs:
  update-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        # Ensure we have full git history and can push back
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .  # Install the package in editable mode
        
    - name: Create data directory
      run: mkdir -p data
        
    - name: Run analysis scripts
      run: |
        python -m utils.get_vol_data
        python -m utils.get_hist_iv
        
    - name: Update README
      run: python -m utils.update_readme
        
    - name: Commit and push changes
      env:
        # Use GitHub Actions token for authentication
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/*.csv README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "Update analysis and README"
        git push
